### PR TITLE
Swap error messages Exist and Format

### PR DESCRIPTION
**Pull request by roerlemans**
These error messages were mixed up

### CODE REVIEW

**Comment by roerlemans** [comment]
@danielebarbaro I made a PR to swap these messages

**Comment by danielebarbaro** [comment]
Hey @roerlemans thanks a lot!

Could you be so kind as to fix the tests as well?

**Comment by roerlemans** [comment]
> Hey @roerlemans thanks a lot!
> 
> Could you be so kind as to fix the tests as well?

Sure! I will fix it tommorrow

**Comment by danielebarbaro** [comment]
well done @roerlemans !

thx a lot for the support

**Pull request merged**
