### PR TITLE
Added support for L9

### PR DESCRIPTION
**Pull request by ssi-anik**

### CODE REVIEW

**Comment by jasperf** [comment]
There were no issues after these changes @ssi-anik ? Well if it works I hope @danielebarbaro can merge this soon as well then. I need of this update as well as several other packages.

**Comment by ssi-anik** [comment]
@jasperf I guess the tests should run somewhere in travis,  idkw but I didn't find it anywhere 🤷🏼‍♂️

**Comment by jasperf** [comment]
@ssi-anik I did see https://github.com/danielebarbaro/laravel-vat-eu-validator/blob/master/.travis.yml so that should work. Also see https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github . But not that familiar with it so perhaps @danielebarbaro has to run it on the repository. Will wait for that.

**Comment by danielebarbaro** [comment]
Hi guys I'm working on a new release for Laravel 8 and Laravel 9.
Thank you a lot @ssi-anik however, this PR is not enough in order to complete the new Laravel compatibility

**Comment by ssi-anik** [comment]
Okay. hope to get a new release soon!

**Comment by danielebarbaro** [comment]
there is a new release :) take a look at tag 1.0.0 :) 

https://github.com/danielebarbaro/laravel-vat-eu-validator/releases/tag/v1.0.0

Now the master branch is ready for L8 and L9

**Comment by ssi-anik** [comment]
Awesome <3

**Pull request closed without merging**
